name: Maven CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'   # ajuste para 17 se o projeto usar Java 17
          cache: maven

      - name: Build & Test (Maven)
        run: mvn -B -ntp -U clean package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/target/*.jar
            !**/original-*.jar

      - name: Upload test reports (Surefire/Failsafe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
